version: '3.9'

services:
  frontend:
    container_name: app-frontend
    build: ./frontend
    working_dir: /app-frontend
    command: npm run dev
    ports:
      - 3000:3000
  backend:
    container_name: app_backend
    build: ./backend
    working_dir: /app-backend
    command: npm run dev
    ports:
      - 3001:3001

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ngcash
      POSTGRES_DB: ngcash_accounts
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      APP_PORT: 3001
    depends_on: 
      - postgres

  postgres:
    image: "postgres:14.5"
    container_name: db_postgres_ngcash
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "ngcash"
      POSTGRES_DB: "ngcash_accounts"
