version: '3'

services:
  postgres:
    image: "postgres:14.5"
    container_name: db_postgres_ngcash
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "ngcash"
      POSTGRES_DB: "ngcash_accounts"



