version: '3'

services:
  backend:
    container_name: app_backend
    build: ./
    ports:
      - 3001:3001
    working_dir: /app-backend
    command: npm run dev
    volumes: 
      - ./src:/app-backend/src
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ngcash
      POSTGRES_DB: ngcash_accounts
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      APP_PORT: 3001

  postgres:
    image: "postgres:14.5"
    container_name: db_postgres_ngcash
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "ngcash"
      POSTGRES_DB: "ngcash_accounts"
